### ISSUE TITLE
Need documentation for Annotation special features

### ISSUE THREAD

**Issue by frankelavsky** [visa/visa-chart-components#32]
The annotations section of the utils readme is okay: https://github.com/visa/visa-chart-components/tree/master/packages/utils#annotations

But the util has a specific feature (that you can add/subtract using nested arrays) that is not documented anywhere. 
This example is powerful and custom to the annotation util wrapper that is built into VCC (Susie Lu's documentation will not teach this feature): `x: [["category1"],["category2]]`

(That example will calculate the pixel value of category2 and subtract it from the calculated pixel value of category1.)

Not only that, but the only explanation of the special features of the util are shown in comments in the example code snippet. It would be nice if there was a table that shows valid things that could be passed to each property (and which properties take precedence over others, such as `x:` versus `data:`).

In addition to this missing piece of documentation in the utils, the documentation in each component only points to d3-annotation by Susie Lu. It does not point to the utils doc (which has additional examples).
Bar chart: https://github.com/visa/visa-chart-components/tree/master/packages/bar-chart#annotation-props

**Comment by chris-demartini** [comment]
This has been addressed in release 6.1.1 that was just pushed.
