### ISSUE TITLE
Alluvial Chart Frequency Values

### ISSUE THREAD

**Issue by brichard1638** [visa/visa-chart-components#51]
The frequency values in the final Alluvial html file are missing. This issue can be replicated by viewing the Alluvial chart provided by the package's code sample.

**Comment by chris-demartini** [comment]
Hi @brichard1638 - I took a quick look into this with the provided demo in `visachartR` and do see the frequency values are present on the links in the Alluvial Diagram, maybe you can provide a screenshot of a simple example and where you see the data from this field is missing? Thanks!

**Comment by brichard1638** [comment]
Chris:::

Thank you for your response!

I have attached a sample of the version of the Alluvial diagram that I see when I use the exact sample code provided in the visachartR example.

Warm regards,

Brice Richard

________________________________

**Comment by chris-demartini** [comment]
This was a great find @brichard1638 , we have reproduced it and will push a fix for it in the next version. Thank you!

**Comment by fkohrt** [comment]
I believe this is the same issue I reported at [#50](https://github.com/visa/visa-chart-components/issues/50#issuecomment-1036231467), so consider that solved as well.

**Comment by brichard1638** [comment]
Florian:::

Thank you for the update!

I look forward to the next updated version of visachartR!

Once released, I will test the issues I initially submitted and provide my feedback, in the hopes that it will confirm and enhance this remarkable package.

Warmest regards,

Brice Richard
Data Scientist
Washington, DC USA
________________________________

**Comment by chris-demartini** [comment]
Good point @fkohrt, @brichard1638 can you please confirm whether the issue Florian calls out is the same one you were referring to? We fixed the issue with our data table that Florian described, so if there is something else here we may not have addressed your concern yet. If there is something else here, please be sure to provide enough detail in your feedback so that we can try to reproduce this on our side. Thanks!

**Comment by chris-demartini** [comment]
released in 6.1.0, closing
