### ISSUE TITLE
npm i @visa/charts-react peer dependency issue (currently fixable with legacy-peer-deps flag)

### ISSUE THREAD

**Issue by davidkutas** [visa/visa-chart-components#63]
If you want to install the `@visa/charts-react` library with the latest `create-react-app`, you get an upstream dependency conflict. I assume that  the `create-react-app` is using `react@18.2.0` while your library is using `react@16.7.0`.

Upon trying to install `charts-react` with the `legacy-peer-deps` flag the installation works perfectly.

**Comment by chris-demartini** [comment]
This was addressed by our most recent release, closing this out.
