### ISSUE TITLE
Not rendering on Voila

### ISSUE THREAD

**Issue by ndgayan** [visa/visa-chart-components#77]
Could you please take a look at this issue?

[Open Browser Console for more detailed log - Double click to close this message]
Model class 'ChartModel' from module '@visa/charts-python' is loaded but can not be instantiated
TypeError: i._deserialize_state is not a function
    at tn._make_model ()

**Comment by david-kutas** [comment]
hi! Thank you for your inputs. I'm one of the maintainers of VCC. Could you please let me know which version of @visa/charts-python you are using?

**Comment by ndgayan** [comment]
Hi @david-kutas,

I'm using pyvisacharts 2.0.0.

In your demo notebook, I got the below error. I think this is related to the compatibility with IPYWidgets 8.0. I saw a lot of 3rd party widgets like Plotly, and IPYCharts failed to load after being updated to IPYWidgets 8.0.

![image](https://user-images.githubusercontent.com/1891059/223746790-60ae10b9-6742-4b3d-85e7-6b5cb8d5fa2e.png)

**Comment by david-kutas** [comment]
Thank you for the info.

We are investigating the issue.

**Comment by david-kutas** [comment]
We just checked on our end, we are using IPYWidgets 7.6.5. With this 7.6.5 version pyvisacharts 2.0.0 works as expected. Can you please test on your end that by downgrading to IPYWidgets 7.6.5 the issue gets resolved? If not, can you please supply more information about your environment (including other packages)?

**Comment by ndgayan** [comment]
I can confirm the charts are working fine on IPYWidgets 7.x.x.

**Comment by david-kutas** [comment]
Thank you for confirming it. We found the reason for the issue. The issue will be resolved with the upcoming new release.

**Comment by chris-demartini** [comment]
This is fixed in the most recent release, closing the issue.
